In [ ]:
#variable
a = 10
print("I am",a,"years old")

I am 10 years old


In [ ]:
#Arthimetic operations of integer values
a=int(input("Enter a value"))
b=int(input("Enter b value"))
print("sum of two numbers is:",a+b)
print("difference is: ",a-b)
print("product is:",a*b)
print("Quotient is:",a/b)
print("Remainder is:",a%b)
print("Power of a to b is: ",a**b)

Enter a value2
Enter b value4
sum of two numbers is: 6
difference is:  -2
product is: 8
Quotient is: 0.5
Remainder is: 2
Power of a to b is:  16


In [ ]:
#Take salary from the user if the salary is more than 50000 there is a 10% tax print his final salary
salary=int(input("Enter you're salary: "))
if(salary>=50000):
  print("youre final salary is: ",salary-(salary*(10/100)))
else:
  print("not tax deduction for youre salary: ",salary)

Enter you're salary: 100000
youre final salary is:  90000.0


In [ ]:
#Get the salary from the user if the salry is more than or equal to 50000 apply 10% tax deduction if the salary is less than 50000 apply 5% tax deduction if the salry is more than 70000 apply 12% tax if salary exist 100000 print you're promoted to next level
salary=int(input("Enter you're salary: "))
if(salary==0):
  print("Entered invalid salary")
elif(salary<50000):
  print("you're final salary after you're salary deduction is: ",salary-(salary*(5/100)))
elif(salary<70000):
  print("you're final salary after you're salary deduction is: ",salary-(salary*(10/100)))
elif(salary<100000):
  print("you're final salary after you're salary deduction is: ",salary-(salary*(12/100)))
else:
  print("you're promoted")

Enter you're salary: 0
Entered invalid salary


In [ ]:
#fOR LOOP
a=int(input("Enter a number: "))
for i in range(1,11):
  print(a,'x',i,'=',a*i)

Enter a number: 25
25 x 1 = 25
25 x 2 = 50
25 x 3 = 75
25 x 4 = 100
25 x 5 = 125
25 x 6 = 150
25 x 7 = 175
25 x 8 = 200
25 x 9 = 225
25 x 10 = 250


In [ ]:
#While loop
a=int(input("Enter the number: "))
i=1
while(i<=10):
  print(a,'x',i,'=',a*i)
  i=i+1

Enter the number: 143
143 x 1 = 143
143 x 2 = 286
143 x 3 = 429
143 x 4 = 572
143 x 5 = 715
143 x 6 = 858
143 x 7 = 1001
143 x 8 = 1144
143 x 9 = 1287
143 x 10 = 1430


In [ ]:
#List Heterogeneous
l1= [1,"kill",89,"chat",9.1,True]
for i in l1:
  print(i)

1
kill
89
chat
9.1
True


In [ ]:
#Mutable:
l1.append("append") #adds elements in the back of the list
print(l1)

[1, 'kill', 89, 'chat', 9.1, True, 'append']


In [ ]:
#inserting element in list:
l1.insert(4,"hi") #insert elements in the list in a particular position
                  #listname.insert(index,element)
print(l1)

[1, 'kill', 89, 'chat', 'hi', 9.1, True, 'append']


In [ ]:
#list extend
l2=['good','Boy','satwik']  #list1.extend(list2)
l1.extend(l2) #l1=l1+l2
print(l1)

[1, 'kill', 89, 'chat', 'hi', 9.1, True, 'append', 'good', 'Boy', 'satwik']


In [ ]:
#deleting element in list
l1.pop(2) #it removes the index element in the list
          #listname.pop(index)
l1.remove(9.1)  #listname.remove(element)
print(l1)

[1, 'kill', 'hi', True, 'append', 'good', 'Boy', 'satwik']


In [ ]:
#clear list
l1.clear()  #clear the list
            #listname.clear()
print(l1)

[]


In [ ]:
#Create a list of 10 random integer elements print their squares save these squares in new list
a=[1,2,3,4,5,6,7,8,9,10]
b=[]
for i in a:
  b.append(i*i)
print(b)




[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [ ]:
#LC
#newlist=[output for]
a=[1,2,3,4,5,6,7,8,9,10]
b=[i*i for i in a]  #list comprehensation
print(b)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [ ]:
#lc
#newlist=[output for if]
a=[23,58,69,47,15,62]
b=[i*i for i in a if i>50]
print(b)

[3364, 4761, 3844]


In [ ]:
#LC
#newlist=[(st of if) if (cond)else (st of else) for]
a=[23,67,12,34,69]
b=[i*i if i>50 else 'x' for i in a]
print(b)

['x', 4489, 'x', 'x', 4761]


In [ ]:
#Take the salary from the user if the salary is less than 50000 10% tax otherwise 15% tax
a=int(input("Enter you're salary: "))
b=[a-a*(10/100) if a<50000 else a-a*(15/100)]
print(b)

Enter you're salary: 75000
[63750.0]


In [ ]:
sal_list=[78000,50400,34000,23000,14000]
res= [i-i*0.1 if i<50000 else i-i*0.15 for i in sal_list] #if if cond else st of else for
print(res)

[66300.0, 42840.0, 30600.0, 20700.0, 12600.0]


In [ ]:
#Create a dictionary
#dictname={key:val,key:val...}
dict1={23:"bala",22:"ajay",24:"om",25:"good boy satwik","mentor":"jwalitha"}
print(dict1)

{23: 'bala', 22: 'ajay', 24: 'om', 25: 'good boy satwik', 'mentor': 'jwalitha'}


In [ ]:
dict3={"dept":'CSE',"details":{"year":"II","sec":'D',"count":71}}
print("year is",dict3["details"]["year"])
print("section is",dict3["details"]["sec"])
print("strength is",dict3["details"]["count"])

year is II
section is D
strength is 71


In [ ]:
idl=[34,56,78,39,100]
names=["joe","suji","rohini","shankar","mani"]
new_zip =(zip(idl,names))
for i in new_zip:
  print(i)

(34, 'joe')
(56, 'suji')
(78, 'rohini')
(39, 'shankar')
(100, 'mani')


In [ ]:
dict1={"dept","year","section","count"}
dict2={"CSE","II","D","71"}
new_zip=(zip(dict1,dict2))
for i in new_zip:
  print(i)

('year', 'II')
('count', 'CSE')
('dept', '71')
('section', 'D')


In [ ]:
#numpy
import numpy as np
a=np.array([1,2,3,4]) #1d array
print(a.ndim)
print(a.shape)


1
(4,)


In [ ]:
import numpy as np
A=np.array([[1,2,3],[4,5,6],[7,8,9]]) #Elements in each row = columns
print(A)
print(A.ndim)
print(A.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)


In [ ]:
#create a 3 dimensional array
import numpy as np
a=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]]])
print(a)
print(a.ndim)
print(a.shape)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]
  [13 14 15]
  [16 17 18]]]
3
(1, 6, 3)


In [ ]:
A=np.array([[[1,2,3],[1,2,3],[4,5,6],[4,5,6]]])
print(A)
print(A.ndim)
print(A.shape)

[[[1 2 3]
  [1 2 3]
  [4 5 6]
  [4 5 6]]]
3
(1, 4, 3)


In [ ]:
A=np.zeros((4,3))
print(A)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#Identity matrice
a=np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
A= np.arange(1,10)
print(A)
print(type(A))

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [ ]:
#print all the numbers that divisible by 8 using a range function between 1 and 1000
A=n.arange(8,1001,8)
print(A)

[   8   16   24   32   40   48   56   64   72   80   88   96  104  112
  120  128  136  144  152  160  168  176  184  192  200  208  216  224
  232  240  248  256  264  272  280  288  296  304  312  320  328  336
  344  352  360  368  376  384  392  400  408  416  424  432  440  448
  456  464  472  480  488  496  504  512  520  528  536  544  552  560
  568  576  584  592  600  608  616  624  632  640  648  656  664  672
  680  688  696  704  712  720  728  736  744  752  760  768  776  784
  792  800  808  816  824  832  840  848  856  864  872  880  888  896
  904  912  920  928  936  944  952  960  968  976  984  992 1000]


In [ ]:
#Linspace
#spliting a range into n numbers with common difference
a=np.linspace(4,80,20)
print(a)

[ 4.  8. 12. 16. 20. 24. 28. 32. 36. 40. 44. 48. 52. 56. 60. 64. 68. 72.
 76. 80.]


#tuples and sets
#document of today



In [ ]:
#tuples
t=(1,2,3,4,5)
print(t)

(1, 2, 3, 4, 5)


In [ ]:
#concat
t1=(1,2,3)+(4,5,6,3)
print(t1)

(1, 2, 3, 4, 5, 6, 3)


In [ ]:
#lenght
print(len(t))

5


In [ ]:
#repetition
t2=("hi! ")*4
print(t2)

hi! hi! hi! hi! 


In [2]:
#updating tuple using list
tl=list(t)
tl[1]=55
t=tuple(tl)
print(t)


NameError: name 't' is not defined

In [4]:
#set operations
s1={1,2,3,4,5}
s2={4,5,6,7,8}
print(s1.union(s2))
print(s1.intersection(s2))
print(s1.difference(s2))
print(s1.symmetric_difference(s2))
print(s1.issubset(s2))
print(s1.issuperset(s2))
print(s1.isdisjoint(s2))

{1, 2, 3, 4, 5, 6, 7, 8}
{4, 5}
{1, 2, 3}
{1, 2, 3, 6, 7, 8}
False
False
False


In [6]:
s={'s',1,'r',2,True}
print(s)
print(len(s))
print(type(s))
s.update("i")
print(s)
s.remove('i')
print(s)
s.pop()
print(s)
s.clear()
print(s)

{1, 2, 's', 'r'}
4
<class 'set'>
{1, 2, 'i', 'r', 's'}
{1, 2, 'r', 's'}
{2, 'r', 's'}
set()
